# Generated by Django 3.2.14 on 2022-08-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='grammar', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_side', models.CharField(max_length=30)),
                ('right_side', models.CharField(max_length=30)),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='grammars.grammar')),
            ],
        ),
    ]
