# Generated by Django 3.2.14 on 2023-01-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammars', '0002_grammar_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='regex',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='rule',
            name='grammar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='grammars.grammar'),
        ),
    ]
